@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor actor
participant "c:Ciudad" as ciudad
participant "4x4:TodoTerreno" as todoTerreno
participant "g:Grilla" as grilla
participant "Accionable" as accionable
actor -> ciudad: <<create>>
ciudad--> actor : c
activate ciudad

loop porUnaCantidadDeMovimientos

actor  -> ciudad : moverVehiculoDerecha()
loop 3
ciudad -> todoTerreno: moverVehiculoDerecha()
ciudad -> grilla : moverVehiculo(moto)

grilla -> todoTerreno : obtenerPosicion()
todoTerreno --> grilla : posicion
grilla -> accionable : accioanar(4x4)
accionable -> todoTerreno :aplicarPenalizacion()

end loop


end
@enduml