@startuml
'https://plantuml.com/sequence-diagram

autonumber

"g:Grilla" -> "pozo : Accionable" : accionar(4x4)
"pozo : Accionable" -> "4x4 : TodoTerreno" : penalizarPorPozo()
"4x4 : TodoTerreno" -> "4x4 : TodoTerreno" : seComioDemasiadosPozos()
"4x4 : TodoTerreno" --> "4x4 : TodoTerreno" : False



@enduml