@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor actor
create "c :Ciudad" as ciudad
participant "moto :Moto" as moto
participant "g :Grilla" as grilla
participant "Accionable" as accionable

activate actor
actor -> ciudad: <<create>>
ciudad --> actor : c
activate ciudad

loop porUnaCantidadDeMovimientos

actor  -> ciudad : moverVehiculoDerecha()
loop 3
ciudad -> moto: moverVehiculoDerecha()
activate moto
ciudad -> grilla : moverVehiculo(moto)
deactivate ciudad
activate grilla
grilla -> moto : obtenerPosicion()
moto --> grilla : posicion
grilla -> accionable : accioanar(moto)
deactivate grilla
activate accionable
accionable -> moto :aplicarPenalizacion()
deactivate accionable
deactivate moto
end loop


end
@enduml