@startuml
'https://plantuml.com/sequence-diagram

participant "g :Grilla" as grilla
participant "pozo :Accionable" as pozo
participant "moto : Moto" as moto

autonumber

activate grilla
grilla ->  pozo : accionar(moto)
deactivate grilla
activate pozo
pozo -> moto : incrementarMovimientosPorObstaculos(3)
deactivate pozo
activate moto
moto -> moto : incrementarMovimientos(3)
activate moto
deactivate moto
deactivate moto

@enduml